<?php
/**
 * ShiftExceptions
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rest Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.x
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * ShiftExceptions Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ShiftExceptions implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ShiftExceptions';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'account_id' => 'int',
        'created_date' => '\DateTime',
        'created_id' => 'int',
        'created_name' => 'string',
        'created_proxy_name' => 'string',
        'event_recurrence_type' => 'string',
        'event_recurrence_value' => 'int',
        'id' => 'int',
        'last_modified_date' => '\DateTime',
        'last_modified_id' => 'int',
        'last_modified_name' => 'string',
        'last_modified_proxy_name' => 'string',
        'organization_id' => 'int',
        'resource_bundle_id' => 'int',
        'scheduling_calendar_id' => 'int',
        'shift_applicability_intervals' => '\Swagger\Client\Model\TimingInterval[]',
        'shift_intervals' => 'string[]',
        'short_id' => 'string',
        'staff_id' => 'int',
        'status' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'account_id' => 'int64',
        'created_date' => 'date-time',
        'created_id' => 'int64',
        'created_name' => null,
        'created_proxy_name' => null,
        'event_recurrence_type' => null,
        'event_recurrence_value' => 'int32',
        'id' => 'int64',
        'last_modified_date' => 'date-time',
        'last_modified_id' => 'int64',
        'last_modified_name' => null,
        'last_modified_proxy_name' => null,
        'organization_id' => 'int64',
        'resource_bundle_id' => 'int64',
        'scheduling_calendar_id' => 'int64',
        'shift_applicability_intervals' => null,
        'shift_intervals' => null,
        'short_id' => null,
        'staff_id' => 'int64',
        'status' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'account_id' => 'accountId',
        'created_date' => 'createdDate',
        'created_id' => 'createdId',
        'created_name' => 'createdName',
        'created_proxy_name' => 'createdProxyName',
        'event_recurrence_type' => 'eventRecurrenceType',
        'event_recurrence_value' => 'eventRecurrenceValue',
        'id' => 'id',
        'last_modified_date' => 'lastModifiedDate',
        'last_modified_id' => 'lastModifiedId',
        'last_modified_name' => 'lastModifiedName',
        'last_modified_proxy_name' => 'lastModifiedProxyName',
        'organization_id' => 'organizationId',
        'resource_bundle_id' => 'resourceBundleId',
        'scheduling_calendar_id' => 'schedulingCalendarId',
        'shift_applicability_intervals' => 'shiftApplicabilityIntervals',
        'shift_intervals' => 'shiftIntervals',
        'short_id' => 'shortId',
        'staff_id' => 'staffId',
        'status' => 'status'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'account_id' => 'setAccountId',
        'created_date' => 'setCreatedDate',
        'created_id' => 'setCreatedId',
        'created_name' => 'setCreatedName',
        'created_proxy_name' => 'setCreatedProxyName',
        'event_recurrence_type' => 'setEventRecurrenceType',
        'event_recurrence_value' => 'setEventRecurrenceValue',
        'id' => 'setId',
        'last_modified_date' => 'setLastModifiedDate',
        'last_modified_id' => 'setLastModifiedId',
        'last_modified_name' => 'setLastModifiedName',
        'last_modified_proxy_name' => 'setLastModifiedProxyName',
        'organization_id' => 'setOrganizationId',
        'resource_bundle_id' => 'setResourceBundleId',
        'scheduling_calendar_id' => 'setSchedulingCalendarId',
        'shift_applicability_intervals' => 'setShiftApplicabilityIntervals',
        'shift_intervals' => 'setShiftIntervals',
        'short_id' => 'setShortId',
        'staff_id' => 'setStaffId',
        'status' => 'setStatus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'account_id' => 'getAccountId',
        'created_date' => 'getCreatedDate',
        'created_id' => 'getCreatedId',
        'created_name' => 'getCreatedName',
        'created_proxy_name' => 'getCreatedProxyName',
        'event_recurrence_type' => 'getEventRecurrenceType',
        'event_recurrence_value' => 'getEventRecurrenceValue',
        'id' => 'getId',
        'last_modified_date' => 'getLastModifiedDate',
        'last_modified_id' => 'getLastModifiedId',
        'last_modified_name' => 'getLastModifiedName',
        'last_modified_proxy_name' => 'getLastModifiedProxyName',
        'organization_id' => 'getOrganizationId',
        'resource_bundle_id' => 'getResourceBundleId',
        'scheduling_calendar_id' => 'getSchedulingCalendarId',
        'shift_applicability_intervals' => 'getShiftApplicabilityIntervals',
        'shift_intervals' => 'getShiftIntervals',
        'short_id' => 'getShortId',
        'staff_id' => 'getStaffId',
        'status' => 'getStatus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const EVENT_RECURRENCE_TYPE_ONCE = 'ONCE';
    const EVENT_RECURRENCE_TYPE_RANGE = 'RANGE';
    const EVENT_RECURRENCE_TYPE_ROTATION_WEEK = 'ROTATION_WEEK';
    const SHIFT_INTERVALS_MONDAY = 'MONDAY';
    const SHIFT_INTERVALS_TUESDAY = 'TUESDAY';
    const SHIFT_INTERVALS_WEDNESDAY = 'WEDNESDAY';
    const SHIFT_INTERVALS_THURSDAY = 'THURSDAY';
    const SHIFT_INTERVALS_FRIDAY = 'FRIDAY';
    const SHIFT_INTERVALS_SATURDAY = 'SATURDAY';
    const SHIFT_INTERVALS_SUNDAY = 'SUNDAY';
    const SHIFT_INTERVALS_EVERYDAY = 'EVERYDAY';
    const STATUS_A = 'A';
    const STATUS_D = 'D';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEventRecurrenceTypeAllowableValues()
    {
        return [
            self::EVENT_RECURRENCE_TYPE_ONCE,
            self::EVENT_RECURRENCE_TYPE_RANGE,
            self::EVENT_RECURRENCE_TYPE_ROTATION_WEEK,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getShiftIntervalsAllowableValues()
    {
        return [
            self::SHIFT_INTERVALS_MONDAY,
            self::SHIFT_INTERVALS_TUESDAY,
            self::SHIFT_INTERVALS_WEDNESDAY,
            self::SHIFT_INTERVALS_THURSDAY,
            self::SHIFT_INTERVALS_FRIDAY,
            self::SHIFT_INTERVALS_SATURDAY,
            self::SHIFT_INTERVALS_SUNDAY,
            self::SHIFT_INTERVALS_EVERYDAY,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_A,
            self::STATUS_D,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['account_id'] = isset($data['account_id']) ? $data['account_id'] : null;
        $this->container['created_date'] = isset($data['created_date']) ? $data['created_date'] : null;
        $this->container['created_id'] = isset($data['created_id']) ? $data['created_id'] : null;
        $this->container['created_name'] = isset($data['created_name']) ? $data['created_name'] : null;
        $this->container['created_proxy_name'] = isset($data['created_proxy_name']) ? $data['created_proxy_name'] : null;
        $this->container['event_recurrence_type'] = isset($data['event_recurrence_type']) ? $data['event_recurrence_type'] : null;
        $this->container['event_recurrence_value'] = isset($data['event_recurrence_value']) ? $data['event_recurrence_value'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['last_modified_date'] = isset($data['last_modified_date']) ? $data['last_modified_date'] : null;
        $this->container['last_modified_id'] = isset($data['last_modified_id']) ? $data['last_modified_id'] : null;
        $this->container['last_modified_name'] = isset($data['last_modified_name']) ? $data['last_modified_name'] : null;
        $this->container['last_modified_proxy_name'] = isset($data['last_modified_proxy_name']) ? $data['last_modified_proxy_name'] : null;
        $this->container['organization_id'] = isset($data['organization_id']) ? $data['organization_id'] : null;
        $this->container['resource_bundle_id'] = isset($data['resource_bundle_id']) ? $data['resource_bundle_id'] : null;
        $this->container['scheduling_calendar_id'] = isset($data['scheduling_calendar_id']) ? $data['scheduling_calendar_id'] : null;
        $this->container['shift_applicability_intervals'] = isset($data['shift_applicability_intervals']) ? $data['shift_applicability_intervals'] : null;
        $this->container['shift_intervals'] = isset($data['shift_intervals']) ? $data['shift_intervals'] : null;
        $this->container['short_id'] = isset($data['short_id']) ? $data['short_id'] : null;
        $this->container['staff_id'] = isset($data['staff_id']) ? $data['staff_id'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getEventRecurrenceTypeAllowableValues();
        if (!is_null($this->container['event_recurrence_type']) && !in_array($this->container['event_recurrence_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'event_recurrence_type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets account_id
     *
     * @return int
     */
    public function getAccountId()
    {
        return $this->container['account_id'];
    }

    /**
     * Sets account_id
     *
     * @param int $account_id account_id
     *
     * @return $this
     */
    public function setAccountId($account_id)
    {
        $this->container['account_id'] = $account_id;

        return $this;
    }

    /**
     * Gets created_date
     *
     * @return \DateTime
     */
    public function getCreatedDate()
    {
        return $this->container['created_date'];
    }

    /**
     * Sets created_date
     *
     * @param \DateTime $created_date created_date
     *
     * @return $this
     */
    public function setCreatedDate($created_date)
    {
        $this->container['created_date'] = $created_date;

        return $this;
    }

    /**
     * Gets created_id
     *
     * @return int
     */
    public function getCreatedId()
    {
        return $this->container['created_id'];
    }

    /**
     * Sets created_id
     *
     * @param int $created_id created_id
     *
     * @return $this
     */
    public function setCreatedId($created_id)
    {
        $this->container['created_id'] = $created_id;

        return $this;
    }

    /**
     * Gets created_name
     *
     * @return string
     */
    public function getCreatedName()
    {
        return $this->container['created_name'];
    }

    /**
     * Sets created_name
     *
     * @param string $created_name created_name
     *
     * @return $this
     */
    public function setCreatedName($created_name)
    {
        $this->container['created_name'] = $created_name;

        return $this;
    }

    /**
     * Gets created_proxy_name
     *
     * @return string
     */
    public function getCreatedProxyName()
    {
        return $this->container['created_proxy_name'];
    }

    /**
     * Sets created_proxy_name
     *
     * @param string $created_proxy_name created_proxy_name
     *
     * @return $this
     */
    public function setCreatedProxyName($created_proxy_name)
    {
        $this->container['created_proxy_name'] = $created_proxy_name;

        return $this;
    }

    /**
     * Gets event_recurrence_type
     *
     * @return string
     */
    public function getEventRecurrenceType()
    {
        return $this->container['event_recurrence_type'];
    }

    /**
     * Sets event_recurrence_type
     *
     * @param string $event_recurrence_type event_recurrence_type
     *
     * @return $this
     */
    public function setEventRecurrenceType($event_recurrence_type)
    {
        $allowedValues = $this->getEventRecurrenceTypeAllowableValues();
        if (!is_null($event_recurrence_type) && !in_array($event_recurrence_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'event_recurrence_type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['event_recurrence_type'] = $event_recurrence_type;

        return $this;
    }

    /**
     * Gets event_recurrence_value
     *
     * @return int
     */
    public function getEventRecurrenceValue()
    {
        return $this->container['event_recurrence_value'];
    }

    /**
     * Sets event_recurrence_value
     *
     * @param int $event_recurrence_value event_recurrence_value
     *
     * @return $this
     */
    public function setEventRecurrenceValue($event_recurrence_value)
    {
        $this->container['event_recurrence_value'] = $event_recurrence_value;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets last_modified_date
     *
     * @return \DateTime
     */
    public function getLastModifiedDate()
    {
        return $this->container['last_modified_date'];
    }

    /**
     * Sets last_modified_date
     *
     * @param \DateTime $last_modified_date last_modified_date
     *
     * @return $this
     */
    public function setLastModifiedDate($last_modified_date)
    {
        $this->container['last_modified_date'] = $last_modified_date;

        return $this;
    }

    /**
     * Gets last_modified_id
     *
     * @return int
     */
    public function getLastModifiedId()
    {
        return $this->container['last_modified_id'];
    }

    /**
     * Sets last_modified_id
     *
     * @param int $last_modified_id last_modified_id
     *
     * @return $this
     */
    public function setLastModifiedId($last_modified_id)
    {
        $this->container['last_modified_id'] = $last_modified_id;

        return $this;
    }

    /**
     * Gets last_modified_name
     *
     * @return string
     */
    public function getLastModifiedName()
    {
        return $this->container['last_modified_name'];
    }

    /**
     * Sets last_modified_name
     *
     * @param string $last_modified_name last_modified_name
     *
     * @return $this
     */
    public function setLastModifiedName($last_modified_name)
    {
        $this->container['last_modified_name'] = $last_modified_name;

        return $this;
    }

    /**
     * Gets last_modified_proxy_name
     *
     * @return string
     */
    public function getLastModifiedProxyName()
    {
        return $this->container['last_modified_proxy_name'];
    }

    /**
     * Sets last_modified_proxy_name
     *
     * @param string $last_modified_proxy_name last_modified_proxy_name
     *
     * @return $this
     */
    public function setLastModifiedProxyName($last_modified_proxy_name)
    {
        $this->container['last_modified_proxy_name'] = $last_modified_proxy_name;

        return $this;
    }

    /**
     * Gets organization_id
     *
     * @return int
     */
    public function getOrganizationId()
    {
        return $this->container['organization_id'];
    }

    /**
     * Sets organization_id
     *
     * @param int $organization_id organization_id
     *
     * @return $this
     */
    public function setOrganizationId($organization_id)
    {
        $this->container['organization_id'] = $organization_id;

        return $this;
    }

    /**
     * Gets resource_bundle_id
     *
     * @return int
     */
    public function getResourceBundleId()
    {
        return $this->container['resource_bundle_id'];
    }

    /**
     * Sets resource_bundle_id
     *
     * @param int $resource_bundle_id resource_bundle_id
     *
     * @return $this
     */
    public function setResourceBundleId($resource_bundle_id)
    {
        $this->container['resource_bundle_id'] = $resource_bundle_id;

        return $this;
    }

    /**
     * Gets scheduling_calendar_id
     *
     * @return int
     */
    public function getSchedulingCalendarId()
    {
        return $this->container['scheduling_calendar_id'];
    }

    /**
     * Sets scheduling_calendar_id
     *
     * @param int $scheduling_calendar_id scheduling_calendar_id
     *
     * @return $this
     */
    public function setSchedulingCalendarId($scheduling_calendar_id)
    {
        $this->container['scheduling_calendar_id'] = $scheduling_calendar_id;

        return $this;
    }

    /**
     * Gets shift_applicability_intervals
     *
     * @return \Swagger\Client\Model\TimingInterval[]
     */
    public function getShiftApplicabilityIntervals()
    {
        return $this->container['shift_applicability_intervals'];
    }

    /**
     * Sets shift_applicability_intervals
     *
     * @param \Swagger\Client\Model\TimingInterval[] $shift_applicability_intervals shift_applicability_intervals
     *
     * @return $this
     */
    public function setShiftApplicabilityIntervals($shift_applicability_intervals)
    {
        $this->container['shift_applicability_intervals'] = $shift_applicability_intervals;

        return $this;
    }

    /**
     * Gets shift_intervals
     *
     * @return string[]
     */
    public function getShiftIntervals()
    {
        return $this->container['shift_intervals'];
    }

    /**
     * Sets shift_intervals
     *
     * @param string[] $shift_intervals shift_intervals
     *
     * @return $this
     */
    public function setShiftIntervals($shift_intervals)
    {
        $allowedValues = $this->getShiftIntervalsAllowableValues();
        if (!is_null($shift_intervals) && array_diff($shift_intervals, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'shift_intervals', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['shift_intervals'] = $shift_intervals;

        return $this;
    }

    /**
     * Gets short_id
     *
     * @return string
     */
    public function getShortId()
    {
        return $this->container['short_id'];
    }

    /**
     * Sets short_id
     *
     * @param string $short_id short_id
     *
     * @return $this
     */
    public function setShortId($short_id)
    {
        $this->container['short_id'] = $short_id;

        return $this;
    }

    /**
     * Gets staff_id
     *
     * @return int
     */
    public function getStaffId()
    {
        return $this->container['staff_id'];
    }

    /**
     * Sets staff_id
     *
     * @param int $staff_id staff_id
     *
     * @return $this
     */
    public function setStaffId($staff_id)
    {
        $this->container['staff_id'] = $staff_id;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($status) && !in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


