<?php
/**
 * WebWidgetWrapper
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rest Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.x
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * WebWidgetWrapper Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WebWidgetWrapper implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'WebWidgetWrapper';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'custom_duration' => 'int',
        'custom_time_unit' => 'string',
        'use_same_duration_as_notification' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'custom_duration' => 'int32',
        'custom_time_unit' => null,
        'use_same_duration_as_notification' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'custom_duration' => 'customDuration',
        'custom_time_unit' => 'customTimeUnit',
        'use_same_duration_as_notification' => 'useSameDurationAsNotification'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'custom_duration' => 'setCustomDuration',
        'custom_time_unit' => 'setCustomTimeUnit',
        'use_same_duration_as_notification' => 'setUseSameDurationAsNotification'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'custom_duration' => 'getCustomDuration',
        'custom_time_unit' => 'getCustomTimeUnit',
        'use_same_duration_as_notification' => 'getUseSameDurationAsNotification'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['custom_duration'] = isset($data['custom_duration']) ? $data['custom_duration'] : null;
        $this->container['custom_time_unit'] = isset($data['custom_time_unit']) ? $data['custom_time_unit'] : null;
        $this->container['use_same_duration_as_notification'] = isset($data['use_same_duration_as_notification']) ? $data['use_same_duration_as_notification'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets custom_duration
     *
     * @return int
     */
    public function getCustomDuration()
    {
        return $this->container['custom_duration'];
    }

    /**
     * Sets custom_duration
     *
     * @param int $custom_duration custom_duration
     *
     * @return $this
     */
    public function setCustomDuration($custom_duration)
    {
        $this->container['custom_duration'] = $custom_duration;

        return $this;
    }

    /**
     * Gets custom_time_unit
     *
     * @return string
     */
    public function getCustomTimeUnit()
    {
        return $this->container['custom_time_unit'];
    }

    /**
     * Sets custom_time_unit
     *
     * @param string $custom_time_unit custom_time_unit
     *
     * @return $this
     */
    public function setCustomTimeUnit($custom_time_unit)
    {
        $this->container['custom_time_unit'] = $custom_time_unit;

        return $this;
    }

    /**
     * Gets use_same_duration_as_notification
     *
     * @return bool
     */
    public function getUseSameDurationAsNotification()
    {
        return $this->container['use_same_duration_as_notification'];
    }

    /**
     * Sets use_same_duration_as_notification
     *
     * @param bool $use_same_duration_as_notification use_same_duration_as_notification
     *
     * @return $this
     */
    public function setUseSameDurationAsNotification($use_same_duration_as_notification)
    {
        $this->container['use_same_duration_as_notification'] = $use_same_duration_as_notification;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


