<?php
/**
 * BroadcastSettingsWrapperTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rest Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.x
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BroadcastSettingsWrapperTest Class Doc Comment
 *
 * @category    Class
 * @description BroadcastSettingsWrapper
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BroadcastSettingsWrapperTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BroadcastSettingsWrapper"
     */
    public function testBroadcastSettingsWrapper()
    {
    }

    /**
     * Test attribute "account_code"
     */
    public function testPropertyAccountCode()
    {
    }

    /**
     * Test attribute "book_conference"
     */
    public function testPropertyBookConference()
    {
    }

    /**
     * Test attribute "confirm"
     */
    public function testPropertyConfirm()
    {
    }

    /**
     * Test attribute "contact_cycles"
     */
    public function testPropertyContactCycles()
    {
    }

    /**
     * Test attribute "cycle_interval"
     */
    public function testPropertyCycleInterval()
    {
    }

    /**
     * Test attribute "deliver_paths"
     */
    public function testPropertyDeliverPaths()
    {
    }

    /**
     * Test attribute "delivery_method_interval"
     */
    public function testPropertyDeliveryMethodInterval()
    {
    }

    /**
     * Test attribute "delivery_path_order"
     */
    public function testPropertyDeliveryPathOrder()
    {
    }

    /**
     * Test attribute "delivery_paths"
     */
    public function testPropertyDeliveryPaths()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "enable_beep"
     */
    public function testPropertyEnableBeep()
    {
    }

    /**
     * Test attribute "enable_record"
     */
    public function testPropertyEnableRecord()
    {
    }

    /**
     * Test attribute "enable_secure_notification"
     */
    public function testPropertyEnableSecureNotification()
    {
    }

    /**
     * Test attribute "enable_smart_conference_confirmation_text"
     */
    public function testPropertyEnableSmartConferenceConfirmationText()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "mobile_settings"
     */
    public function testPropertyMobileSettings()
    {
    }

    /**
     * Test attribute "push_custom_fields"
     */
    public function testPropertyPushCustomFields()
    {
    }

    /**
     * Test attribute "recipient_app"
     */
    public function testPropertyRecipientApp()
    {
    }

    /**
     * Test attribute "require_pin_for_message"
     */
    public function testPropertyRequirePinForMessage()
    {
    }

    /**
     * Test attribute "resident_connection_delivery_paths"
     */
    public function testPropertyResidentConnectionDeliveryPaths()
    {
    }

    /**
     * Test attribute "resource_url"
     */
    public function testPropertyResourceUrl()
    {
    }

    /**
     * Test attribute "response_setting"
     */
    public function testPropertyResponseSetting()
    {
    }

    /**
     * Test attribute "secure_push_instructions"
     */
    public function testPropertySecurePushInstructions()
    {
    }

    /**
     * Test attribute "sender_caller_infos"
     */
    public function testPropertySenderCallerInfos()
    {
    }

    /**
     * Test attribute "sender_email"
     */
    public function testPropertySenderEmail()
    {
    }

    /**
     * Test attribute "sender_sms_infos"
     */
    public function testPropertySenderSmsInfos()
    {
    }

    /**
     * Test attribute "sms_call_back"
     */
    public function testPropertySmsCallBack()
    {
    }

    /**
     * Test attribute "throttl_default_amount"
     */
    public function testPropertyThrottlDefaultAmount()
    {
    }

    /**
     * Test attribute "throttle"
     */
    public function testPropertyThrottle()
    {
    }

    /**
     * Test attribute "validate_contacts"
     */
    public function testPropertyValidateContacts()
    {
    }

    /**
     * Test attribute "validate_contacts_by_organization"
     */
    public function testPropertyValidateContactsByOrganization()
    {
    }

    /**
     * Test attribute "voice_mail_option"
     */
    public function testPropertyVoiceMailOption()
    {
    }
}
