<?php
/**
 * ContactPathWrapperTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rest Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.x
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ContactPathWrapperTest Class Doc Comment
 *
 * @category    Class
 * @description ContactPathWrapper
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ContactPathWrapperTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ContactPathWrapper"
     */
    public function testContactPathWrapper()
    {
    }

    /**
     * Test attribute "country_code"
     */
    public function testPropertyCountryCode()
    {
    }

    /**
     * Test attribute "path_enable"
     */
    public function testPropertyPathEnable()
    {
    }

    /**
     * Test attribute "path_id"
     */
    public function testPropertyPathId()
    {
    }

    /**
     * Test attribute "phone_ext"
     */
    public function testPropertyPhoneExt()
    {
    }

    /**
     * Test attribute "quiet_time_frames"
     */
    public function testPropertyQuietTimeFrames()
    {
    }

    /**
     * Test attribute "skip_validation"
     */
    public function testPropertySkipValidation()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "system_requirement"
     */
    public function testPropertySystemRequirement()
    {
    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {
    }

    /**
     * Test attribute "wait_time"
     */
    public function testPropertyWaitTime()
    {
    }
}
