<?php
/**
 * ContactFilterRuleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rest Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.x
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ContactFilterRuleTest Class Doc Comment
 *
 * @category    Class
 * @description ContactFilterRule
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ContactFilterRuleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ContactFilterRule"
     */
    public function testContactFilterRule()
    {
    }

    /**
     * Test attribute "attribute_id"
     */
    public function testPropertyAttributeId()
    {
    }

    /**
     * Test attribute "attribute_values"
     */
    public function testPropertyAttributeValues()
    {
    }

    /**
     * Test attribute "column_name"
     */
    public function testPropertyColumnName()
    {
    }

    /**
     * Test attribute "column_value"
     */
    public function testPropertyColumnValue()
    {
    }

    /**
     * Test attribute "contact_field_id"
     */
    public function testPropertyContactFieldId()
    {
    }

    /**
     * Test attribute "contact_filter_id"
     */
    public function testPropertyContactFilterId()
    {
    }

    /**
     * Test attribute "contact_filter_option"
     */
    public function testPropertyContactFilterOption()
    {
    }

    /**
     * Test attribute "data_type"
     */
    public function testPropertyDataType()
    {
    }

    /**
     * Test attribute "display_name"
     */
    public function testPropertyDisplayName()
    {
    }

    /**
     * Test attribute "embedded_column_name"
     */
    public function testPropertyEmbeddedColumnName()
    {
    }

    /**
     * Test attribute "field_value"
     */
    public function testPropertyFieldValue()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "search_field_display_type"
     */
    public function testPropertySearchFieldDisplayType()
    {
    }

    /**
     * Test attribute "seq"
     */
    public function testPropertySeq()
    {
    }

    /**
     * Test attribute "table_name"
     */
    public function testPropertyTableName()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "value_category"
     */
    public function testPropertyValueCategory()
    {
    }

    /**
     * Test attribute "variable_id"
     */
    public function testPropertyVariableId()
    {
    }
}
