<?php
/**
 * ContactAddressInstanceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rest Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.x
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ContactAddressInstanceTest Class Doc Comment
 *
 * @category    Class
 * @description ContactAddressInstance
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ContactAddressInstanceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ContactAddressInstance"
     */
    public function testContactAddressInstance()
    {
    }

    /**
     * Test attribute "arrive_date"
     */
    public function testPropertyArriveDate()
    {
    }

    /**
     * Test attribute "asset_external_id"
     */
    public function testPropertyAssetExternalId()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "expire_date"
     */
    public function testPropertyExpireDate()
    {
    }

    /**
     * Test attribute "gis_location"
     */
    public function testPropertyGisLocation()
    {
    }

    /**
     * Test attribute "iata"
     */
    public function testPropertyIata()
    {
    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {
    }

    /**
     * Test attribute "location_name"
     */
    public function testPropertyLocationName()
    {
    }

    /**
     * Test attribute "location_source"
     */
    public function testPropertyLocationSource()
    {
    }

    /**
     * Test attribute "location_source_id"
     */
    public function testPropertyLocationSourceId()
    {
    }

    /**
     * Test attribute "new_asset_id"
     */
    public function testPropertyNewAssetId()
    {
    }

    /**
     * Test attribute "postal_code"
     */
    public function testPropertyPostalCode()
    {
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "street_address"
     */
    public function testPropertyStreetAddress()
    {
    }

    /**
     * Test attribute "suite"
     */
    public function testPropertySuite()
    {
    }
}
