<?php
/**
 * FormVariableItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rest Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.x
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FormVariableItemTest Class Doc Comment
 *
 * @category    Class
 * @description FormVariableItem
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FormVariableItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FormVariableItem"
     */
    public function testFormVariableItem()
    {
    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "created_date"
     */
    public function testPropertyCreatedDate()
    {
    }

    /**
     * Test attribute "created_id"
     */
    public function testPropertyCreatedId()
    {
    }

    /**
     * Test attribute "created_name"
     */
    public function testPropertyCreatedName()
    {
    }

    /**
     * Test attribute "created_proxy_name"
     */
    public function testPropertyCreatedProxyName()
    {
    }

    /**
     * Test attribute "edit_value_on_ui"
     */
    public function testPropertyEditValueOnUi()
    {
    }

    /**
     * Test attribute "ext_properties"
     */
    public function testPropertyExtProperties()
    {
    }

    /**
     * Test attribute "form_id"
     */
    public function testPropertyFormId()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "incident_id"
     */
    public function testPropertyIncidentId()
    {
    }

    /**
     * Test attribute "incident_phase_id"
     */
    public function testPropertyIncidentPhaseId()
    {
    }

    /**
     * Test attribute "is_required"
     */
    public function testPropertyIsRequired()
    {
    }

    /**
     * Test attribute "is_sys"
     */
    public function testPropertyIsSys()
    {
    }

    /**
     * Test attribute "is_used"
     */
    public function testPropertyIsUsed()
    {
    }

    /**
     * Test attribute "last_modified_date"
     */
    public function testPropertyLastModifiedDate()
    {
    }

    /**
     * Test attribute "last_modified_id"
     */
    public function testPropertyLastModifiedId()
    {
    }

    /**
     * Test attribute "last_modified_name"
     */
    public function testPropertyLastModifiedName()
    {
    }

    /**
     * Test attribute "last_modified_proxy_name"
     */
    public function testPropertyLastModifiedProxyName()
    {
    }

    /**
     * Test attribute "organization_id"
     */
    public function testPropertyOrganizationId()
    {
    }

    /**
     * Test attribute "phase_template_id"
     */
    public function testPropertyPhaseTemplateId()
    {
    }

    /**
     * Test attribute "prefix_name"
     */
    public function testPropertyPrefixName()
    {
    }

    /**
     * Test attribute "previous_val"
     */
    public function testPropertyPreviousVal()
    {
    }

    /**
     * Test attribute "required"
     */
    public function testPropertyRequired()
    {
    }

    /**
     * Test attribute "resource_bundle_id"
     */
    public function testPropertyResourceBundleId()
    {
    }

    /**
     * Test attribute "seq"
     */
    public function testPropertySeq()
    {
    }

    /**
     * Test attribute "short_id"
     */
    public function testPropertyShortId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "sys"
     */
    public function testPropertySys()
    {
    }

    /**
     * Test attribute "template_form_id"
     */
    public function testPropertyTemplateFormId()
    {
    }

    /**
     * Test attribute "template_id"
     */
    public function testPropertyTemplateId()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "used"
     */
    public function testPropertyUsed()
    {
    }

    /**
     * Test attribute "val"
     */
    public function testPropertyVal()
    {
    }

    /**
     * Test attribute "validate_max_len"
     */
    public function testPropertyValidateMaxLen()
    {
    }

    /**
     * Test attribute "variable_id"
     */
    public function testPropertyVariableId()
    {
    }

    /**
     * Test attribute "variable_item"
     */
    public function testPropertyVariableItem()
    {
    }

    /**
     * Test attribute "variable_name"
     */
    public function testPropertyVariableName()
    {
    }

    /**
     * Test attribute "variable_value"
     */
    public function testPropertyVariableValue()
    {
    }
}
