<?php
/**
 * GroupWrapperTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rest Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.x
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GroupWrapperTest Class Doc Comment
 *
 * @category    Class
 * @description GroupWrapper
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GroupWrapperTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GroupWrapper"
     */
    public function testGroupWrapper()
    {
    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "calendar_id"
     */
    public function testPropertyCalendarId()
    {
    }

    /**
     * Test attribute "created_date"
     */
    public function testPropertyCreatedDate()
    {
    }

    /**
     * Test attribute "created_id"
     */
    public function testPropertyCreatedId()
    {
    }

    /**
     * Test attribute "created_name"
     */
    public function testPropertyCreatedName()
    {
    }

    /**
     * Test attribute "created_proxy_name"
     */
    public function testPropertyCreatedProxyName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "dirty"
     */
    public function testPropertyDirty()
    {
    }

    /**
     * Test attribute "enable_sequenced_contact"
     */
    public function testPropertyEnableSequencedContact()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "last_modified_date"
     */
    public function testPropertyLastModifiedDate()
    {
    }

    /**
     * Test attribute "last_modified_id"
     */
    public function testPropertyLastModifiedId()
    {
    }

    /**
     * Test attribute "last_modified_name"
     */
    public function testPropertyLastModifiedName()
    {
    }

    /**
     * Test attribute "last_modified_proxy_name"
     */
    public function testPropertyLastModifiedProxyName()
    {
    }

    /**
     * Test attribute "last_modified_time"
     */
    public function testPropertyLastModifiedTime()
    {
    }

    /**
     * Test attribute "last_synchronized_time"
     */
    public function testPropertyLastSynchronizedTime()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "organization_id"
     */
    public function testPropertyOrganizationId()
    {
    }

    /**
     * Test attribute "parent_id"
     */
    public function testPropertyParentId()
    {
    }

    /**
     * Test attribute "processing_state"
     */
    public function testPropertyProcessingState()
    {
    }

    /**
     * Test attribute "resource_bundle_id"
     */
    public function testPropertyResourceBundleId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }
}
