<?php
/**
 * IncidentTemplateWrapperTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rest Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.x
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * IncidentTemplateWrapperTest Class Doc Comment
 *
 * @category    Class
 * @description IncidentTemplateWrapper
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IncidentTemplateWrapperTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IncidentTemplateWrapper"
     */
    public function testIncidentTemplateWrapper()
    {
    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "created_date"
     */
    public function testPropertyCreatedDate()
    {
    }

    /**
     * Test attribute "created_id"
     */
    public function testPropertyCreatedId()
    {
    }

    /**
     * Test attribute "created_name"
     */
    public function testPropertyCreatedName()
    {
    }

    /**
     * Test attribute "created_proxy_name"
     */
    public function testPropertyCreatedProxyName()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "last_modified_date"
     */
    public function testPropertyLastModifiedDate()
    {
    }

    /**
     * Test attribute "last_modified_id"
     */
    public function testPropertyLastModifiedId()
    {
    }

    /**
     * Test attribute "last_modified_name"
     */
    public function testPropertyLastModifiedName()
    {
    }

    /**
     * Test attribute "last_modified_proxy_name"
     */
    public function testPropertyLastModifiedProxyName()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "organization_id"
     */
    public function testPropertyOrganizationId()
    {
    }

    /**
     * Test attribute "phase_templates"
     */
    public function testPropertyPhaseTemplates()
    {
    }

    /**
     * Test attribute "resource_bundle_id"
     */
    public function testPropertyResourceBundleId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "template_status"
     */
    public function testPropertyTemplateStatus()
    {
    }
}
