<?php
/**
 * LaunchPolicyWrapperTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rest Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.x
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LaunchPolicyWrapperTest Class Doc Comment
 *
 * @category    Class
 * @description LaunchPolicyWrapper
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LaunchPolicyWrapperTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LaunchPolicyWrapper"
     */
    public function testLaunchPolicyWrapper()
    {
    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "created_date"
     */
    public function testPropertyCreatedDate()
    {
    }

    /**
     * Test attribute "created_id"
     */
    public function testPropertyCreatedId()
    {
    }

    /**
     * Test attribute "created_name"
     */
    public function testPropertyCreatedName()
    {
    }

    /**
     * Test attribute "created_proxy_name"
     */
    public function testPropertyCreatedProxyName()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "last_modified_date"
     */
    public function testPropertyLastModifiedDate()
    {
    }

    /**
     * Test attribute "last_modified_id"
     */
    public function testPropertyLastModifiedId()
    {
    }

    /**
     * Test attribute "last_modified_name"
     */
    public function testPropertyLastModifiedName()
    {
    }

    /**
     * Test attribute "last_modified_proxy_name"
     */
    public function testPropertyLastModifiedProxyName()
    {
    }

    /**
     * Test attribute "launch_setting"
     */
    public function testPropertyLaunchSetting()
    {
    }

    /**
     * Test attribute "notification"
     */
    public function testPropertyNotification()
    {
    }

    /**
     * Test attribute "organization_id"
     */
    public function testPropertyOrganizationId()
    {
    }

    /**
     * Test attribute "resource_bundle_id"
     */
    public function testPropertyResourceBundleId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "task_status"
     */
    public function testPropertyTaskStatus()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }
}
