<?php
/**
 * NotificationResultWrapperTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Rest Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.x
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * NotificationResultWrapperTest Class Doc Comment
 *
 * @category    Class
 * @description NotificationResultWrapper
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NotificationResultWrapperTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "NotificationResultWrapper"
     */
    public function testNotificationResultWrapper()
    {
    }

    /**
     * Test attribute "all_details"
     */
    public function testPropertyAllDetails()
    {
    }

    /**
     * Test attribute "confirmed_count"
     */
    public function testPropertyConfirmedCount()
    {
    }

    /**
     * Test attribute "confirmed_late_count"
     */
    public function testPropertyConfirmedLateCount()
    {
    }

    /**
     * Test attribute "not_confirmed_count"
     */
    public function testPropertyNotConfirmedCount()
    {
    }

    /**
     * Test attribute "notification_id"
     */
    public function testPropertyNotificationId()
    {
    }

    /**
     * Test attribute "polling_details"
     */
    public function testPropertyPollingDetails()
    {
    }

    /**
     * Test attribute "total_count"
     */
    public function testPropertyTotalCount()
    {
    }

    /**
     * Test attribute "unreachable_count"
     */
    public function testPropertyUnreachableCount()
    {
    }
}
